version: '3.8'

services:
  weather-zipcode-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge