version: '3.8'

services:
  weather-zipcode-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=81729b82816247ab84f171740252004
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge