POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Product 2",
    "price": 100
}

###
GET http://localhost:8000/products/65742a64-a1ae-432b-aad0-307d9bd3c195 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/65742a64-a1ae-432b-aad0-307d9bd3c195 HTTP/1.1
Content-Type: application/json

{
    "name": "Produto atualizado",
    "price": 99
}

